wino:
  request-mapping: ny/wino/v1
  preload: false
  cache:
    initial-capacity: 500
    expiration-time: 30
  photo:
#    location: /root/media
    location: D:\MyPictures

server:
  port: 8080

springdoc:
  use-management-port: false
  show-actuator: true
  api-docs:
    groups:
      enabled: true

spring:
  application:
    name: wino-club
    version: 0.0.0-SNAPSHOT
    id: 10304
    org: lanina

  h2:
    console:
      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-other: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

  profiles:
    group:
      default:
        - local
      local:
        - basic-oauth
        - h2
        - data

logging.level:
  'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': trace
  'logging.level.org.springframework.web': debug
  'root' : info