wino:
  request-mapping: ny/wino/v1
  preload: false
  photo:
    location: C:\Users\alexlanin\MyPictures

server:
  port: 8080

springdoc:
  use-management-port: false

spring:
  h2:
    console:
      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-other: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1